services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8007:8003"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
